name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Clonacion de codigo
        uses: actions/checkout@v4
     
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with: 
          java-version: '17'
          distribution: 'temurin'
      
     
          
      - name: Compilar y ejecutar pruebas
        run: | 
          mvn clean test

      - name: Generar informe de cobertura con Jacoco
        run: |
          mvn jacoco:report

      - name: Subir informe de cobertura de código
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html 
  
    
        
